Updated dotfiles

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,12 +1,15 @@
 #!/usr/bin/env sh
 
 progress () {
-    echo -e -n " $1\r"
+    echo -e -n "\e[33m $1\e[0m\r"
 }
 
 completed () {
-    echo -e -n " $1\n"
+    echo -e -n "\e[32m $1\e[0m\n"
 }
+
+# Stop on error.
+set -e
 
 progress "Setting env vars"
 SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
@@ -14,15 +17,15 @@ COUNT=0
 FILE_CNT=$(find lib ! -path lib -type f | wc -l)
 completed
 
-progress "Making directories"
 # Required paths for vim and mpd
+progress "Making directories"
 mkdir -p ~/.vim/tmp/undo
 mkdir -p ~/.vim/tmp/backup
 mkdir -p ~/.vim/tmp/swap
 mkdir -p ~/.config/mpd/res
 mkdir -p ~/.config/mpd/res/playlists
 touch ~/.config/mpd/log
-completed " Making directories"
+completed "Making directories"
 
 # Symlink and backup all files in ./lib
 find lib ! -path lib -type f | while read FILE; do
@@ -48,6 +51,8 @@ completed "Updated $COUNT/$FILE_CNT symlinks"
 progress "Setup vim plug"
 [[ -f ~/.vim/autoload/plug.vim ]] || curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
 [[ -f ~/.local/share/nvim/site/autoload/plug.vim ]] || curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+/usr/bin/vim +PlugInstall +PlugClean +qall
+/usr/bin/nvim +PlugInstall +PlugClean +qall
 completed "Setup vim plug"
 
 progress "Setup oh-my-zsh"
@@ -55,17 +60,15 @@ progress "Setup oh-my-zsh"
 [[ -d ~/.config/.oh-my-zsh/custom/plugins/zsh-autosuggestions ]] || git clone https://github.com/zsh-users/zsh-autosuggestions ~/.config/.oh-my-zsh/custom/plugins/zsh-autosuggestions
 [[ -d ~/.config/.oh-my-zsh/custom/plugins/zsh-completions ]] || git clone https://github.com/zsh-users/zsh-completions ~/.config/.oh-my-zsh/custom/plugins/zsh-completions
 [[ -d ~/.config/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting ]] || git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.config/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
-
 completed "Setup Oh-my-zsh"
 
-# VIM & NVIM plugins
-/usr/bin/vim +PlugInstall +PlugClean +qall
-/usr/bin/nvim +PlugInstall +PlugClean +qall
-
 # Update font cache.
+progress "Setup fonts"
 fc-cache
+completed "Setup fonts"
 
 # Setup user services.
+progress "Start user services"
 systemctl enable --user synccal.timer
 systemctl restart --user synccal.timer
 systemctl enable --user sync_music.timer
@@ -76,17 +79,9 @@ systemctl enable --user bing-wallpaper.service
 systemctl restart --user bing-wallpaper.service
 systemctl enable --user mbsync.timer
 systemctl restart --user mbsync.timer
-
-# Refresh DWM bar.
-#refdwmbar
-
-# Rebuild DWM.
-#cd $HOME/doc/src/github.com/kruhlmann/dwm/
-#git pull
-#git add .
-#git commit -am "Updated through dotfiles (https://github.com/Kruhlmann/dotfiles)"
-#git push
-#sudo make install
+completed "Start user services"
 
 # Rebuild and restart Xmonad.
+progress "Building Xmonad"
 xmonad --recompile; xmonad --restart
+completed "Building Xmonad"
